In [36]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd

In [37]:
## load the model 
model = load_model("./regression.keras")

C:\Users\ashis\AppData\Roaming\Python\Python312\site-packages\keras\src\saving\saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 8 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [38]:
## load the pickle files
with open("label_encoder_gender.pkl","rb") as file:
    label_encoder_gender = pickle.load(file)

with open("onehot_encoder_geo.pkl","rb") as file:
    onehot_encoder_geo = pickle.load(file)

with open("scaler.pkl","rb") as file:
    scaler = pickle.load(file)

In [39]:
## input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'Exited': 0
}

In [50]:
## transform the features
input_data['Gender']=label_encoder_gender.transform([input_data['Gender']])[0]
input_data

{'CreditScore': 600,
 'Geography': 'France',
 'Gender': 0,
 'Age': 40,
 'Tenure': 3,
 'Balance': 60000,
 'NumOfProducts': 2,
 'HasCrCard': 1,
 'IsActiveMember': 1,
 'Exited': 0}

In [55]:
geo_encoded = onehot_encoder_geo.transform([[input_data["Geography"]]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out())
geo_encoded_df

C:\Users\ashis\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [59]:
input_df = pd.DataFrame([input_data])
input_df = pd.concat([input_df.drop(columns=["Geography"],axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,600,0,40,3,60000,2,1,1,0,1.0,0.0,0.0

In [61]:
## make predictions
results = model.predict(input_df)
print(results[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1033376300.0