In [2]:
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
## read the csv file 
data = pd.read_csv("./Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## preprocess the data
## drop unecessary columns
data = data.drop(columns = ["RowNumber","CustomerId","Surname"],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [10]:
## using Label Encoder convert categorical Gender data into nominal form
label_encoder_gender = LabelEncoder()
data["Gender"] = label_encoder_gender.fit_transform(data["Gender"])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [14]:
## similarly convert geography data into one-hot encoded vectors
onehot_encoder_geo = OneHotEncoder()
encoded_geo = onehot_encoder_geo.fit_transform(data[["Geography"]]).toarray()
encoded_geo

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [15]:
## convert it into dataframe
lables = onehot_encoder_geo.get_feature_names_out()
encoded_geo_df = pd.DataFrame(encoded_geo,columns=lables)
encoded_geo_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [17]:
## drop the Geography column and append the new vectors as it as columns
data = data.drop(columns=["Geography"],axis=1)
data = pd.concat([data,encoded_geo_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [18]:
data.shape

(10000, 13)

In [19]:
## divide into dependent and independent features
X = data.drop(columns=["EstimatedSalary"],axis=1)
y = data["EstimatedSalary"]

In [20]:
## train and test split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [58]:
## scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
## save in pickle files
with open("label_encoder_gender.pkl","wb") as file:
    pickle.dump(label_encoder_gender,file)

with open("onehot_encoder_geo.pkl","wb") as file:
    pickle.dump(onehot_encoder_geo,file)

with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

In [31]:
## ANN Regression
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
from datetime import datetime

In [ ]:
## create a model
model = Sequential([
    Dense(64,activation="relu",input_shape =(X_train.shape[1],)),
    Dense(32,activation="relu"),
    Dense(1) ##output layer; a linear output to be produced
])

##add optimisers, loss functions, metrics
##default learning rate is 0.001
model.compile(optimizer = "Adam", loss = "mean_absolute_error", metrics = ["mse","mae"])

C:\Users\ashis\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [33]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [42]:
## set up tensorboard and early stopping
log_dir = "logs/fit/"+datetime.now().strftime("%Y/%m/%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)
earlystopping_callback = EarlyStopping(monitor = "val_loss",patience=10,restore_best_weights=True)

In [45]:
## train the model
history = model.fit(
    X_train,
    y_train,
    validation_data =(X_test,y_test),
    epochs = 100,
    callbacks = [tensorboard_callback,earlystopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 101386.3750 - mae: 101386.3750 - mse: 13626743808.0000 - val_loss: 98502.2266 - val_mae: 98502.2266 - val_mse: 13003832320.0000
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99723.9688 - mae: 99723.9688 - mse: 13258170368.0000 - val_loss: 96863.6406 - val_mae: 96863.6406 - val_mse: 12679437312.0000
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 98261.1406 - mae: 98261.1406 - mse: 12896778240.0000 - val_loss: 92685.0547 - val_mae: 92685.0547 - val_mse: 11853146112.0000
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91825.6406 - mae: 91825.6406 - mse: 11704095744.0000 - val_loss: 85739.6797 - val_mae: 85739.6797 - val_mse: 10476768256.0000
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 85532.5859 - mae: 85532.5859 - mse: 10419341312.0000 - val_loss: 76894.3750 - val_mae: 76894.3750 - val_mse: 8722541568.0000
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 75803.6328 - mae: 75803.6328 - mse: 8455469056.0000 - val_loss: 67839.5859 - val_mae: 67839.5859 - val_mse: 6909564416.0000
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 65792.1094 - mae: 65792.1094 - mse: 6520535552.0000 - val_loss: 60234.8516 - val_mae: 60234.8516 - val_mse: 5385154560.0000
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 60057.2812 - mae: 60057.2812 - mse: 5319049216.0000 - val_loss: 55041.4766 - val_mae: 55041.4766 - val_mse: 4372427776.0000
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54869.8594 - mae: 54869.8594 - mse: 4322103808.0000 - val_loss: 52299.5234 - val_mae: 52299.5234 - val_mse: 3833991936.0000
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52135.4141 - mae: 52135.4141 - mse: 3785724928.0000 - val_loss: 51222.9688 - val_mae: 51222.9688 - val_mse: 3612363008.0000
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50982.3555 - mae: 50982.3555 - mse: 3565917952.0000 - val_loss: 50899.9141 - val_mae: 50899.9141 - val_mse: 3543693824.0000
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50851.2031 - mae: 50851.2031 - mse: 3536301312.0000 - val_loss: 50789.7539 - val_mae: 50789.7539 - val_mse: 3516895744.0000
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50602.2930 - mae: 50602.2930 - mse: 3500241408.0000 - val_loss: 50742.1406 - val_mae: 50742.1406 - val_mse: 3504401920.0000
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50899.0703 - mae: 50899.0703 - mse: 3506406912.0000 - val_loss: 50704.4531 - val_mae: 50704.4531 - val_mse: 3495172608.0000
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50143.6562 - mae: 50143.6562 - mse: 3438325248.0000 - val_loss: 50672.2773 - val_mae: 50672.2773 - val_mse: 3487527424.0000
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50646.4688 - mae: 50646.4688 - mse: 3471101184.0000 - val_loss: 50647.0781 - val_mae: 50647.0781 - val_mse: 3481286400.0000
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49981.0078 - mae: 49981.0078 - mse: 3394182912.0000 - val_loss: 50615.7617 - val_mae: 50615.7617 - val_mse: 3474357248.0000
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50575.3398 - mae: 50575.3398 - mse: 3459863552.0000 - val_loss: 50598.1055 - val_mae: 50598.1055 - val_mse: 3468783616.0000
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49788.5781 - mae: 49788.5781 - mse: 3384797440.0000 - val_loss: 50581.4219 - val_mae: 50581.4219 - val_mse: 3464324608.0000
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50109.1289 - mae: 50109.1289 - mse: 3422851328.0000 - val_loss: 50543.9531 - val_mae: 50543.9531 - val_mse: 3457046272.0000
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50029.5352 - mae: 50029.5352 - mse: 3404233728.0000 - val_loss: 50522.4375 - val_mae: 50522.4375 - val_mse: 3452114432.0000
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49941.2969 - mae: 49941.2969 - mse: 3381581824.0000 - val_loss: 50503.1953 - val_mae: 50503.1953 - val_mse: 3447549440.0000
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49689.8867 - mae: 49689.8867 - mse: 3361899264.0000 - val_loss: 50498.9531 - val_mae: 50498.9531 - val_mse: 3445359360.0000
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50063.7383 - mae: 50063.7383 - mse: 3397184000.0000 - val_loss: 50474.2188 - val_mae: 50474.2188 - val_mse: 3440932864.0000
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 50042.5547 - mae: 50042.5547 - mse: 3400800256.0000 - val_loss: 50470.7305 - val_mae: 50470.7305 - val_mse: 3438794752.0000
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49510.3789 - mae: 49510.3789 - mse: 3326395904.0000 - val_loss: 50457.1367 - val_mae: 50457.1367 - val_mse: 3435220736.0000
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49704.6211 - mae: 49704.6211 - mse: 3355707136.0000 - val_loss: 50448.9844 - val_mae: 50448.9844 - val_mse: 3432813568.0000
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49920.4258 - mae: 49920.4258 - mse: 3378635264.0000 - val_loss: 50443.1953 - val_mae: 50443.1953 - val_mse: 3431004928.0000
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49744.5898 - mae: 49744.5898 - mse: 3346832896.0000 - val_loss: 50434.6758 - val_mae: 50434.6758 - val_mse: 3429036544.0000
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49492.0547 - mae: 49492.0547 - mse: 3335561728.0000 - val_loss: 50429.8398 - val_mae: 50429.8398 - val_mse: 3426846720.0000
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49402.4297 - mae: 49402.4297 - mse: 3317021696.0000 - val_loss: 50407.5938 - val_mae: 50407.5938 - val_mse: 3422973696.0000
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49981.4492 - mae: 49981.4492 - mse: 3385951744.0000 - val_loss: 50404.7773 - val_mae: 50404.7773 - val_mse: 3422508032.0000
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49233.6172 - mae: 49233.6172 - mse: 3308231168.0000 - val_loss: 50395.7930 - val_mae: 50395.7930 - val_mse: 3419653888.0000
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49483.6992 - mae: 49483.6992 - mse: 3317262592.0000 - val_loss: 50399.8008 - val_mae: 50399.8008 - val_mse: 3419298816.0000
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49561.0234 - mae: 49561.0234 - mse: 3326905344.0000 - val_loss: 50387.6953 - val_mae: 50387.6953 - val_mse: 3416384256.0000
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 49870.8047 - mae: 49870.8047 - mse: 3354292480.0000 - val_loss: 50395.5195 - val_mae: 50395.5195 - val_mse: 3416461312.0000
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49219.6523 - mae: 49219.6523 - mse: 3296998400.0000 - val_loss: 50391.7383 - val_mae: 50391.7383 - val_mse: 3415462144.0000
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49445.0820 - mae: 49445.0820 - mse: 3321540352.0000 - val_loss: 50373.8008 - val_mae: 50373.8008 - val_mse: 3412314880.0000
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49692.6250 - mae: 49692.6250 - mse: 3345192704.0000 - val_loss: 50374.8633 - val_mae: 50374.8633 - val_mse: 3411902464.0000
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49705.7188 - mae: 49705.7188 - mse: 3351459840.0000 - val_loss: 50379.4570 - val_mae: 50379.4570 - val_mse: 3411492608.0000
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49488.7773 - mae: 49488.7773 - mse: 3323871744.0000 - val_loss: 50369.7852 - val_mae: 50369.7852 - val_mse: 3409921024.0000
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49181.1719 - mae: 49181.1719 - mse: 3293659392.0000 - val_loss: 50363.9258 - val_mae: 50363.9258 - val_mse: 3408386816.0000
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49730.9609 - mae: 49730.9609 - mse: 3329461248.0000 - val_loss: 50359.3164 - val_mae: 50359.3164 - val_mse: 3407122176.0000
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49338.8438 - mae: 49338.8438 - mse: 3302068480.0000 - val_loss: 50357.2812 - val_mae: 50357.2812 - val_mse: 3405993472.0000
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49210.7148 - mae: 49210.7148 - mse: 3280817408.0000 - val_loss: 50364.4922 - val_mae: 50364.4922 - val_mse: 3406599168.0000
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49562.1602 - mae: 49562.1602 - mse: 3328502784.0000 - val_loss: 50356.7695 - val_mae: 50356.7695 - val_mse: 3404990720.0000
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49882.5977 - mae: 49882.5977 - mse: 3350418176.0000 - val_loss: 50351.4219 - val_mae: 50351.4219 - val_mse: 3403770368.0000
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50030.1406 - mae: 50030.1406 - mse: 3382052096.0000 - val_loss: 50355.3242 - val_mae: 50355.3242 - val_mse: 3403624704.0000
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49287.9180 - mae: 49287.9180 - mse: 3283634176.0000 - val_loss: 50355.6953 - val_mae: 50355.6953 - val_mse: 3403710976.0000
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49278.2578 - mae: 49278.2578 - mse: 3303623424.0000 - val_loss: 50341.6094 - val_mae: 50341.6094 - val_mse: 3401468672.0000
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49282.8438 - mae: 49282.8438 - mse: 3299536640.0000 - val_loss: 50342.0938 - val_mae: 50342.0938 - val_mse: 3400977920.0000
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49829.7461 - mae: 49829.7461 - mse: 3364465920.0000 - val_loss: 50344.6992 - val_mae: 50344.6992 - val_mse: 3400889344.0000
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49078.6445 - mae: 49078.6445 - mse: 3280782592.0000 - val_loss: 50347.3594 - val_mae: 50347.3594 - val_mse: 3401442304.0000
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49783.2031 - mae: 49783.2031 - mse: 3350671616.0000 - val_loss: 50340.8789 - val_mae: 50340.8789 - val_mse: 3400375296.0000
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48877.8906 - mae: 48877.8906 - mse: 3252949248.0000 - val_loss: 50334.1797 - val_mae: 50334.1797 - val_mse: 3399013120.0000
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49973.7539 - mae: 49973.7539 - mse: 3357051136.0000 - val_loss: 50333.6992 - val_mae: 50333.6992 - val_mse: 3398945280.0000
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48724.4609 - mae: 48724.4609 - mse: 3228358400.0000 - val_loss: 50343.5312 - val_mae: 50343.5312 - val_mse: 3400105984.0000
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49010.3125 - mae: 49010.3125 - mse: 3267258624.0000 - val_loss: 50339.2852 - val_mae: 50339.2852 - val_mse: 3398807808.0000
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49266.9219 - mae: 49266.9219 - mse: 3293512448.0000 - val_loss: 50344.2578 - val_mae: 50344.2578 - val_mse: 3399510272.0000
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49314.5781 - mae: 49314.5781 - mse: 3314106368.0000 - val_loss: 50346.0195 - val_mae: 50346.0195 - val_mse: 3399557888.0000
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48987.0586 - mae: 48987.0586 - mse: 3261985536.0000 - val_loss: 50348.5625 - val_mae: 50348.5625 - val_mse: 3399634432.0000
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49775.6562 - mae: 49775.6562 - mse: 3364755456.0000 - val_loss: 50333.1914 - val_mae: 50333.1914 - val_mse: 3397514496.0000
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48935.5664 - mae: 48935.5664 - mse: 3266018048.0000 - val_loss: 50336.8398 - val_mae: 50336.8398 - val_mse: 3398225664.0000
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49563.2578 - mae: 49563.2578 - mse: 3332367616.0000 - val_loss: 50351.2188 - val_mae: 50351.2188 - val_mse: 3399557376.0000
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49550.2227 - mae: 49550.2227 - mse: 3328350976.0000 - val_loss: 50351.0234 - val_mae: 50351.0234 - val_mse: 3399648768.0000
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49846.0000 - mae: 49846.0000 - mse: 3343950848.0000 - val_loss: 50341.6641 - val_mae: 50341.6641 - val_mse: 3398607104.0000
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48645.6758 - mae: 48645.6758 - mse: 3224836864.0000 - val_loss: 50333.9688 - val_mae: 50333.9688 - val_mse: 3397177088.0000
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49576.0859 - mae: 49576.0859 - mse: 3328475392.0000 - val_loss: 50341.9297 - val_mae: 50341.9297 - val_mse: 3398302720.0000
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49264.0039 - mae: 49264.0039 - mse: 3294063360.0000 - val_loss: 50327.8477 - val_mae: 50327.8477 - val_mse: 3396397056.0000
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49297.9609 - mae: 49297.9609 - mse: 3306178048.0000 - val_loss: 50339.5156 - val_mae: 50339.5156 - val_mse: 3397700096.0000
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49232.7773 - mae: 49232.7773 - mse: 3298167552.0000 - val_loss: 50344.8086 - val_mae: 50344.8086 - val_mse: 3398117632.0000
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49568.5156 - mae: 49568.5156 - mse: 3323168512.0000 - val_loss: 50329.6680 - val_mae: 50329.6680 - val_mse: 3396218368.0000
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49573.6992 - mae: 49573.6992 - mse: 3331351552.0000 - val_loss: 50341.5742 - val_mae: 50341.5742 - val_mse: 3397727488.0000
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49654.1719 - mae: 49654.1719 - mse: 3323257856.0000 - val_loss: 50332.4766 - val_mae: 50332.4766 - val_mse: 3396616448.0000
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48753.6094 - mae: 48753.6094 - mse: 3249775360.0000 - val_loss: 50343.1445 - val_mae: 50343.1445 - val_mse: 3397929984.0000
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49332.8672 - mae: 49332.8672 - mse: 3292333824.0000 - val_loss: 50347.5742 - val_mae: 50347.5742 - val_mse: 3398269440.0000
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49111.4883 - mae: 49111.4883 - mse: 3292257792.0000 - val_loss: 50333.4844 - val_mae: 50333.4844 - val_mse: 3396306432.0000
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48586.5469 - mae: 48586.5469 - mse: 3230649600.0000 - val_loss: 50335.0391 - val_mae: 50335.0391 - val_mse: 3396560640.0000
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49451.7266 - mae: 49451.7266 - mse: 3298221824.0000 - val_loss: 50333.3789 - val_mae: 50333.3789 - val_mse: 3396268032.0000

In [46]:
from tensorboard import program

# Set the path to your logs directory (adjust if needed)
log_dir = "logs/fit"

# Create and launch the TensorBoard server
tb = program.TensorBoard()
tb.configure(argv=[None, "--logdir", log_dir])
url = tb.launch()

print(f"✅ TensorBoard is running at: {url}")

✅ TensorBoard is running at: http://localhost:6006/

In [50]:
## evaluate test data metrics
test_metrics = model.evaluate(X_test,y_test)
print(test_metrics)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51105.5977 - mae: 51105.5977 - mse: 3473819648.0000
[50327.84765625, 3396397056.0, 50327.84765625]

In [52]:
model.save("regression.keras")

In [53]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0